---
title: "Sim Data Analysis"
format: html
---


```{r}
library(ggplot2)
library(dplyr)
library(pscl)
library(MASS)
library(performance)

data <- read.csv("sim_data.csv")

# Mental health visits
data |> ggplot(aes(x = AMVSum)) +
  geom_histogram(bins=round(max(data$AMVSum)/3))

# # By race
data |> group_by(raceth) |>
  summarize(mean_visits = mean(AMVSum)) |>
  ggplot(aes(x = raceth, y = mean_visits)) +
  geom_bar(stat = "identity") +
  scale_x_continuous(breaks = c(1,2,3,4,5,6,7), labels = c("Af Am", "Hispanic", "Mid Eastern", "Cauc-Other", "Cauc-Jewish", "Asian", "Nat Am/Pac Isl")) 

# By income
data |> group_by(incomecat) |>
  summarize(mean_visits = mean(AMVSum)) |>
  ggplot(aes(x = incomecat, y = mean_visits)) +
  geom_bar(stat = "identity") +
  scale_x_continuous(breaks = c(1,2,3,4,5,6,7), labels = c("< 25k", "25k-50k", "50k-75k", "75k-100k", "100k-125k", "125-150k", "> 150k"))

# By gender
data |> group_by(genderbinary) |>
  summarize(mean_visits = mean(AMVSum)) |>
  ggplot(aes(x = genderbinary, y = mean_visits)) +
  geom_bar(stat = "identity") +
  scale_x_continuous(breaks = c(0,1), labels = c("F", "M"))
 
# By age
data |> group_by(agecat) |>
  summarize(mean_visits = mean(AMVSum)) |>
  ggplot(aes(x = agecat, y = mean_visits)) +
  geom_bar(stat = "identity") +
  scale_x_continuous(breaks = c(1,2,3,4,5,6), labels = c(">65", "55-64", "45-54", "35-44", "25-34", "18-24"))


# Model example

model1 <- glm(AMVSum ~ factor(genderbinary), family= poisson(link = "log"), data=data)
summary(model1)


performance::check_overdispersion(model1)
performance::check_zeroinflation(model1)

exp(model1$coefficients)

```

We have good reason to believe there will be a lot of zeros in the data, so we will use a zero-inflated model.

We also have a good reason to believe there is overdispersion, so we will use a negative binomial model.

```{r}

model1_nb <- zeroinfl(AMVSum ~ factor(genderbinary) | factor(genderbinary), data=data, dist="negbin")

summary(model1_nb)
```
